# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    - &OnlinePayOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OnlinePayOrg

        # ID to load the MSP definition as
        ID: OnlinePayMSP

        MSPDir: ../mymsp/orgmsp/peer0.onlinepay.example.com/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OnlinePayMSP.admin', 'OnlinePayMSP.peer', 'OnlinePayMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('OnlinePayMSP.admin', 'OnlinePayMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('OnlinePayMSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.onlinepay.example.com
              Port: 7051
